### ISSUE TITLE
plot3d.py

### ISSUE THREAD

**Issue by junyuewang** [FABLE-3DXRD/ImageD11#23]
Got error when indexing -> plot x/y/z:

Got wavelength from gv file of  0.153684
Got wedge from gv file of  0.0
Read your gv file containing (2, 3)
DEBUG    : python return array
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1544, in __call__
    return self.func(*args)
  File "/home/junyue/.local/lib/python2.7/site-packages/ImageD11/guiindexer.py", line 154, in plotxyz
    self.plot3d = plot3d.plot3d(self.parent,gv)
  File "/home/junyue/.local/lib/python2.7/site-packages/ImageD11/plot3d.py", line 84, in __init__
    if data!=None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by junyuewang** [comment]
I tried both, all work, thanks!

**Comment by jonwright** [comment]
Great, thanks for letting me know. I'll close the issue and do a release this week.
