### ISSUE TITLE
Get rid of the shared memory arrays : add a colfile mmap option

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/ImageD11#265]
In sinograms/properties.py and sinograms/point_by_point.py the code works via shared memory.
This does not scale beyond one node and it fails on python2.7.

For global read-only memory we could use mmap with numpy on a non-compressed hdf5 file (https://gist.github.com/maartenbreddels/09e1da79577151e5f7fec660c209f06e):

```
assert dset.chunks is None and dset.compression is None and dset.is_virtual is None and dset.is_external is None and etc.
file = open(path, "rb")
fileno = file.fileno()
mapping = mmap.mmap(fileno, 0, access=mmap.ACCESS_READ)
np.frombuffer(mapping, dtype=dset.dtype, count=dset.size, offset=dset.id.get_offset()).reshape(dset.shape)
```

This may be useful for reducing some out-of-memory problems. 

Another upgrade path could be looking into dask.dataframe for distributed processing.

**Comment by jonwright** [comment]
Note : multiprocessing + shared memory seems to be buggy. The remove from tracker monkeypatch does not work. Abandon it.
```
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/cvmfs/hpc.esrf.fr/software/packages/linux/x86_64/jupyter-slurm/2023.10.7/envs/jupyter-slurm/lib/python3.11/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/hpc.esrf.fr/software/packages/linux/x86_64/jupyter-slurm/2023.10.7/envs/jupyter-slurm/lib/python3.11/multiprocessing/synchronize.py", line 87, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by jonwright** [comment]
There is still the evil monkeypatch in properties.py

**Comment by jonwright** [comment]
Within #389 the monkeypatch is suppressed by:
`if os.environ.get('IMAGED11_PATCH_MP', None) != 'MONKEYPATCH':`

This is not ideal, but it appears to run with or without the patch in cases where the code works. This could be about cleanup during OOM problems.

Cleaning all this up would be a natural case for also developing #252

**Comment by jonwright** [comment]
ping: needed by @jadball to get a localmax working on 2D -> 3D or 4D.

Simplified plan:
- save cf_2d labels with sparse pixels (add a cplabel or lmlabel column)
- write out some graph saving peak overlap links across sinogram directions (e.g omega or dty)
- give the links a direction (uphill)
- label maxima
- do the graph traversal reading labels

**Comment by jonwright** [comment]
... on reflection ... there should be 2D -> 4D labelling code in frelon_peaksearch that might work already
