### ISSUE TITLE
Error when calling grid_index_parallel

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#79]
I'm receiving an error message when I try to use the grid_index_parallel module inside a custom script I am writing.

Instead of specifying the input flt file, par file etc from the command line, I am setting them separately:

```
from ImageD11.grid_index_parallel import grid_index_parallel
clean_peaks = '/path/to/cleanpeaks.flt'
optimized_pars = '/path/to/optimized_pars.par'
gridpars = {
    "DSTOL": 0.035,
    "OMEGAFLOAT": 0.5,
    "COSTOL": 0.002,
    "NPKS": 40,
    "TOLSEQ": [0.02, 0.015, 0.01],
    "SYMMETRY": "cubic",
    "RING1": [1, 0],
    "RING2": [1, 0],
    "NUL": True,
    "FITPOS": True,
    "tolangle": 0.5,
    "toldist": 172 * 2,
}
translations = [
    (t_x, t_y, t_z)
    for t_x in range(-600, 601, 400)
    for t_y in range(-600, 601, 400)
    for t_z in range(-600, 601, 400)
]

<code snipped>

if indexed:
    print("Already indexed!")
else:
    random.seed(int(time.time()))
    random.shuffle(translations)
    grid_index_parallel(clean_peaks, optimized_pars, 'out', gridpars, translations)
```

My custom script has it's own input and output arguments which are formatted differently than usual.
The rest of my code runs fine, but when we drop into multithreading:
```
WARNING:root:titles are sc  fc  omega
WARNING:root:titles are sc  fc  omega
Done init
Using a pool of 15 processes
Hello from ForkPoolWorker-1 7277 5 to doout.flt 95664
Hello from ForkPoolWorker-2 7278 5 to doout.flt 95664
Hello from ForkPoolWorker-4 7280 5 to doout.flt 95664
Hello from ForkPoolWorker-3 7279 5 to doout.flt 95664
Hello from ForkPoolWorker-5 7281 4 to doout.flt 95664
Hello from ForkPoolWorker-6 7282 4 to doout.flt 95664
Hello from ForkPoolWorker-7 7283 4 to doout.flt 95664
Hello from ForkPoolWorker-9 7285 4 to doout.flt 95664
Hello from ForkPoolWorker-8 7284 4 to doout.flt 95664
Hello from ForkPoolWorker-10 7286 4 to doout.flt 95664
Hello from ForkPoolWorker-11 7287 4 to doout.flt 95664
Hello from ForkPoolWorker-12 7288 4 to doout.flt 95664
Hello from ForkPoolWorker-13 7289 4 to doout.flt 95664
Hello from ForkPoolWorker-14 7290 4 to doout.flt 95664
Hello from ForkPoolWorker-15 7291 4 to doout.flt 95664
WARNING:root:titles are sc  fc  omega
WARNING:root:titles are sc  fc  omega
Caught exception in worker thread
Traceback (most recent call last):
  File "lib/python3.7/site-packages/ImageD11/grid_index_parallel.py", line 245, in wrap_test_many_points
    test_many_points( x )
  File "lib/python3.7/site-packages/ImageD11/grid_index_parallel.py", line 146, in test_many_points
    mytransformer.loadfileparameters(  parameters )
  File "lib/python3.7/site-packages/ImageD11/transformer.py", line 242, in loadfileparameters
    self.parameterobj.loadparameters(filename)
  File "lib/python3.7/site-packages/xfab/parameters.py", line 183, in loadparameters
    lines = open(filename,"r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: '95664'
```

This number '95664' is actually sys.argv[2] in my script, so it feels like somehow that's getting passed to the grid_index_parallel module.

Any ideas?

Thanks for your continued help.

**Comment by jadball** [comment]
I believe the issue is probably here:

https://github.com/FABLE-3DXRD/ImageD11/blob/d3e4b23c0db31845b9b6fda7c40af46c4a7cad5d/ImageD11src/grid_index_parallel.py#L262
https://github.com/FABLE-3DXRD/ImageD11/blob/d3e4b23c0db31845b9b6fda7c40af46c4a7cad5d/ImageD11src/grid_index_parallel.py#L274-L282

sys.argv[2] in line 279 I think needs changing to parfile?

**Comment by jonwright** [comment]
Looks like a bug to me.
The example script also needs to include an if __name__=="__main__" section for using multiprocessing on windows. There was a related problem. I will send a fix if I get some time, but a pull request is always welcome.
Thanks for tracking it down!
