### ISSUE TITLE
Error when parsing makemap options with argparse

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/ImageD11#89]
I am trying to parse the arguments for makemap.py so that I can call it in my wrapper function.

When I parse the arguments with argparse:

```
from argparse import Namespace, ArgumentParser
from makemap import makemap as go_make
from makemap import get_options as get_map_options
map_parser = get_map_options(parser)
map_options, args = map_parser.parse_known_args()
```

I receive the following error message:

```
Traceback (most recent call last):
  File "auto_single_letterbox.py", line 166, in <module>
    map_parser = get_map_options(parser)
  File "/.../ImageD11/scripts/makemap.py", line 63, in get_options
    parser = ImageD11.refinegrains.get_options(parser)
  File ".../site-packages/ImageD11/refinegrains.py", line 87, in get_options
    help="Name of input parameter file")
  File ".../argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File ".../argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File ".../argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File ".../argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File ".../argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File ".../argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -p/--parfile: conflicting option string: -p
```

**Comment by jadball** [comment]
Solved, sorry about that. I had to redeclare the ArgumentParser as I had previously used it to parse arguments for peaksearch:

```
parser = ArgumentParser()
ps_parser = peaksearcher.get_options(parser)
ps_options, args = ps_parser.parse_known_args()
ps_args = []
...
parser = ArgumentParser()
map_parser = get_map_options(parser)
map_options, args = map_parser.parse_known_args()
map_args = []
```
